const data = {
    products:[
        {
            _id:'1',
            name:'PlayStation 5',
            category:'Console',
            image:'/images/p1.jpg',
            price: 499,
            countInStock: 10,
            brand:'Sony',
            rating: 5,
            numReviews: 11386,
            description:'high quality product',
        },
    
        {
            _id:'2',
            name:'Xbox Series X',
            category:'Console',
            image:'/images/p2.jpg',
            price: 499,
            countInStock: 100,
            brand:'Microsoft',
            rating: 4.5,
            numReviews: 5454,
            description:'high quality product',
        },
    
        {
            _id:'3',
            name:'Nintendo Switch',
            category:'Console',
            image:'/images/p3.jpg',
            price: 369,
            countInStock: 102,
            brand:'Sony',
            rating: 5,
            numReviews: 65625,
            description:'high quality product',
        },
    
        {
            _id:'4',
            name:'MSI MEG Trident X 10SD-864US SFF',
            category:'PC',
            image:'/images/p4.jpg',
            price: 2487.46,
            countInStock: 310,
            brand:'MSI',
            rating: 4.6,
            numReviews: 40,
            description:'high quality product',
        },
    
        {
            _id:'5',
            name:'Cyberpunk 2077 - PlayStation 4',
            category:'Video Game',
            image:'/images/p5.jpg',
            price: 59.99,
            countInStock: 0,
            brand:'CD Projekt RED',
            rating: 4,
            numReviews: 1270,
            description:'high quality product',
        },
    
        {
            _id:'6',
            name:'Samsung Galaxy S21 Ultra',
            category:'Electronic',
            image:'/images/p6.jpg',
            price: 1349,
            countInStock: 100,
            brand:'SAMSUNG',
            rating: 5,
            numReviews: 1,
            description:'high quality product',
        },

        {
            _id:'7',
            name:'Assassin’s Creed Valhalla Standard Edition',
            category:'Video Games',
            image:'/images/p7.jpg',
            price: 59.99,
            countInStock: 275,
            brand:'Ubisoft',
            rating: 4.5,
            numReviews: 7493,
            description:'high quality product',
        },

        {
            _id:'8',
            name:`The Last of Us Part II Collector's Edition`,
            category:'Video Games',
            image:'/images/p8.jpg',
            price: 179.99,
            countInStock: 26,
            brand:'PlayStation',
            rating: 4,
            numReviews: 1122,
            description:'high quality product',
        },

        {
            _id: '9',
            name: `Marvel's Avengers for PlayStation 4`,
            category: 'Video Games',
            image: '/images/p9.jpg',
            price: 59.99,
            countInStock: 100,
            brand:'Square Enix',
            rating: 4.5,
            numReviews: 5706,
            description:'high quality product',
        },

        {
            _id:'10',
            name:'The Legend of Zelda: Breath of the Wild',
            category:'Video Games',
            image:'/images/p10.jpg',
            price: 59.99,
            countInStock: 3,
            brand:'Nintendo',
            rating: 5,
            numReviews: 32911,
            description:'high quality product',
        },
    ],
};

export default data;